TigerReports:
  Version: 1.7+ spigot
  Author: MrTigreroux
  Description: Management of reports / Gestion de signalements.
Config:
  ColorCharacter: '&'
  # Character used for colors in messages.yml / Caractère utilisé pour les couleurs dans messages.yml
  
  LineBreakSymbol: "//"
  # Symbol used to separate lines in messages.yml / Symbole utilisé pour séparer les lignes dans messages.yml
  
  InfoLanguage: French
  # Language used in info messages of the plugin like warnings in the console and /tigerreports help command / Langue utilisée pour les messages d'information comme les avertissements dans la console et la commande d'aide /tigerreports
  # Only 2 languages available : French and English / Seulement 2 langues disponibles : French et English
  
  Time: default
  # Time of a city to use (example: "America/Chicago"), list of available cities here: / Temps d'une ville à utiliser (exemple: "Europe/Paris"), la liste des villes possibles est ici:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # Set 'default' to use the default server time / Mettre "default" pour utiliser le temps par défaut du serveur
  
  PermissionRequired: no
  # Permission needed to use /report command / Permission requise pour utiliser la commande /report
  
  ReportOnline: no
  # Report only online players / Signaler uniquement des joueurs connectés
  
  MaxReports: 100
  # Maximum amount of saved reports, others are just displayed in the chat / Nombre maximum de signalements sauvegardés, les autres sont simplement affichés dans le chat
  
  MinCharacters: 3
  # Minimum amount of characters in the reason of a report / Nombre minimum de caractères pour la raison d'un signalement
  
  ReportCooldown: 300
  # Cooldown in seconds between each report / Temps d'attente en secondes entre chaque signalement
  
  ReportedImmunity: 120
  # Time in seconds during which the reported player cannot be reported again / Temps en secondes durant lequel un joueur signalé ne peut être à nouveau signalé
  
  AutoCommands: none
  # List of commands to execute with the console after a report, set 'none' to don't execute any / Liste des commandes à exécuter avec la console après chaque signalement, mettre "none" pour aucune
  # Usable placeholders:    _Id_, _Server_, _Date_, _Reporter_, _Reported_ and _Reason_
  
  AutoCommandsBeforeTeleportation: none
  # - vanish
  # List of commands to execute before a staff teleports himself to the location of the participant of a report / Liste des commandes à exécuter avant qu'un membre de la modération ne se téléporte à la position d'un participant d'un signalement
  # Put '-CONSOLE' at the beginning of a command to execute it with the console (and not the staff member) / Mettre "-CONSOLE" au début d'une commande pour l'exécuter avec la console (et non le membre de la modération)
  # Usable placeholders: _Id_ (id of the report), _Reported_ (reported player name), _Reporter_ (reporter player name, the command is executed for each reporter if they are multiple), _Staff_ (name of the staff who teleports himself) and _Reason_ (reason of the report) / Données utilisables: _Id_ (identifiant du signalement), _Reported_ (pseudo du joueur signalé), _Reporter_ (pseudo du joueur signaleur, la commande est exécutée pour chaque signaleur s'il y en a plusieurs), _Staff_ (pseudo du membre de la modération qui se téléporte) et _Reason_ (raison du signalement)
  
  AbusiveReport:
    Cooldown: 3600
    # Cooldown in seconds inflicted for an abusive report / Temps d'attente en secondes infligé pour un signalement abusif
  
    Commands: none
    # List of executed commands after a report is processed as abusive, set 'none' to don't execute any / Liste des commandes exécutées après chaque signalement traité comme abusif, mettre "none" pour aucune
    # Put '-CONSOLE' at the beginning of a command to execute it with the console (and not the staff member) / Mettre "-CONSOLE" au début d'une commande pour l'exécuter avec la console (et non le membre de la modération)
    # Usable placeholders:    _Id_ (id of the report), _Reported_ (reported player name), _Reporter_ (reporter player name, the command is executed for each reporter if they are multiple), _Staff_ (processor staff name) and _Reason_ (reason of the report and therefore not necessarily the name of the default reason) / Données utilisables: _Id_ (identifiant du signalement), _Reported_ (pseudo du joueur signalé), _Reporter_ (pseudo du joueur signaleur, la commande est exécutée pour chaque signaleur s'il y en a plusieurs), _Staff_ (pseudo du membre du staff qui traite le signalement) et _Reason_ (raison du signalement et donc pas forcément le nom de la sanction par défaut)
  
  MessagesHistory: 5
  # Amount of saved messages / Nombre de messages sauvegardés
  
  CommandsHistory: none
  # - msg
  # - tell
  # List of saved commands in messages history, set 'none' to don't save any / Liste des commandes sauvegardées dans l'historique des messages, mettre "none" pour aucune
  
  StackReports: yes
  # Group reports against the same player for the same reason / Regrouper les signalements contre un même joueur pour une même raison
  
  NotifyStackedReports: yes
  # Notify staff members of same reports against the same player / Informer les membres de l'équipe des mêmes signalements envoyés contre un même joueur
  
  UpdateDateOfStackedReports: no
  # Update the report date of stacked reports (against the same player for the same reason) at each new report / Mettre à jour la date des signalements groupés (envoyés contre un même joueur pour une même raison) à chaque nouveau signalement
  
  Notifications:
    Delay: 2
    # Time in seconds before sending the notification after the connection of the user / Délai en secondes avant d'envoyer la notification après la connexion de l'utilisateur
    
    Players: true
    # Notify players about the decisions made on their reports / Informer les joueurs des décisions prises sur leurs signalements
    
    Staff:
      Connection: yes
      # Display at staff connection / Afficher à la connexion d'un membre de l'équipe
      
      MinutesInterval: 0
      # Display each x minutes, set 0 to disable / Afficher toutes les x minutes, mettre 0 pour désactiver
    # Notifications about reports to process / Notifications à propos des signalements à traiter
  
  OnlyDoneArchives: no
  # Prevent archive of unprocessed reports / Empêcher l'archivage de signalements non traités
  
  MenuUpdatesInterval: 10
  # Update opened menus each x seconds / Actualiser les menus ouverts toutes les x secondes
  
  MenuSound: ENTITY_ITEM_PICKUP
  ErrorSound: ENTITY_ITEM_BREAK
  ReportSound: ENTITY_BAT_DEATH
  TeleportSound: ENTITY_ENDERMEN_TELEPORT
  StaffSound: ENTITY_ITEM_PICKUP
  # Bukkit sounds used on specific actions / Sons bukkit utilisés pour certaines actions
  # Set 'none' to disable the sound / Mettre "none" pour désactiver le son
  
  CustomReasons: yes
  # Allow custom reasons / Autoriser les raisons personnalisées
  
  CollectSkulls: yes
  # Collect player's skull from Mojang. If disabled the skulls will have no skin / Collecter les têtes de joueurs depuis Mojang. Si désactivé, les têtes n'auront pas d'apparence (skin).
  
  DefaultReasons:
    Reason1:
      Name: "Fly"
      Lore: "&7Le joueur se d\xe9place dans//&7les airs."
      # "&7The player is flying. "
      Item: Material-Feather
      PunishCommands:
      - "ban _Reported_ 7d Fly"
  #    - '-CONSOLE title @a title {"text":""}'
  #    - '-CONSOLE title @a subtitle ["",{"text":"_Reported_","color":"red"},{"text":" a \u00e9t\u00e9 banni pour: ","color":"gray"},{"text":"Fly","color":"yellow"}]'
  #    - '-CONSOLE tellraw _Staff_ {"text":"Vous avez sanctionn\u00e9 le joueur _Reported_"}'
  #    - '-CONSOLE eco give _Reporter_ 5'
      PunishCommandsPermission: punishment.fly
    Reason2:
      Name: "Speed"
      Lore: "&7Le joueur se d\xe9place anormalement//&7vite."
      # "&7The player is moving too quick."
      Item: Material-Chainmail_leggings
      PunishCommands:
      - "ban _Reported_ 7d Speed"
    Reason3:
      Name: "ForceField"
      Lore: "&7Le joueur tape les joueurs/entit\xe9s//&7proches de lui de fa\u00E7on suspecte."
      # "&7The player is hitting players/entities//&7abnormally."
      Item: Material-Iron_sword
      PunishCommands:
      - "ban _Reported_ 14d ForceField"
    Reason4:
      Name: "Reach"
      Lore: "&7Le joueur tape de tr\u00E8s loin//&7les joueurs/entit\xe9s."
      # "&7The player is hitting entities from far away."
      Item: Material-Stick
      PunishCommands:
      - "ban _Reported_ 7d Reach"
    Reason5:
      Name: "RapidBowShot"
      Lore: "&7Le joueur tire des fl\u00E8ches//&7tr\u00E8s vite."
      # "&7The player is shooting arrows quickly."
      Item: Material-Bow
      PunishCommands:
      - "ban _Reported_ 7d RapidBowShot"
    Reason6:
      Name: "NoKnockback"
      Lore: "&7Le joueur ne recule pas//&7lorsqu'il est frapp\xe9."
      # "&7The player isn't knocked//&7back when he is hit."
      Item: Material-Fishing_rod
      PunishCommands:
      - "ban _Reported_ 7d NoKnockback"
    Reason7: blank
    Reason8:
      Name: "Grief"
      Lore: "&7Le joueur a d\xe9grad\xe9 une de//&7mes constructions."
      # "&7The player griefed one of my construction."
      Item: Material-TNT
      PunishCommands:
      - "ban _Reported_ 2d Grief"
    Reason9:
      Name: "Insultes"
      Lore: "&7Le joueur est irrespectueux."
      # "&7The player is disrespectful."
      Item: Material-Sign
      PunishCommands:
      - "mute _Reported_ 2h Insultes"
  # Default reasons displayed in a menu / Raisons par défaut affichées dans un menu
  # Put 'blank' to create an empty reason (to add a space in the menu) / Mettre "blank" pour créer une raison vide (pour ajouter un espace dans le menu)
  # Name:    Reason of the report / Raison du signalement
  # Lore:    Description of the report / Description du signalement
  # Item:    Material-<item_type>(:damage) or/ou Skull-<pseudo>
  #   Examples:    Material-Stone = Stone / Pierre    Material-Wool:2 = Magenta Wool / Laine magenta    Skull-MrTigreroux = Skull of player MrTigreroux / Tête du joueur MrTigreroux
  #   Material names (used for <item_type> placeholder) depend on the Spigot version used on your server.
  #     Spigot 1.8 material names: https://helpch.at/docs/1.8/org/bukkit/Material.html
  #     Spigot 1.13 material names: https://helpch.at/docs/1.13/org/bukkit/Material.html
  #     Spigot latest version material names: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # PunishCommands:    List of commands to execute when punishing / Liste des commandes à exécuter lors d'une sanction.
  #                    Put '-CONSOLE' at the beginning of a command to execute it with the console (and not the staff member) / Mettre "-CONSOLE" au début d'une commande pour l'exécuter avec la console (et non le membre de la modération)
  #                    Usable placeholders: _Id_ (id of the report), _Reported_ (reported player name), _Reporter_ (reporter player name, the command is executed for each reporter if they are multiple), _Staff_ (processor staff name) and _Reason_ (reason of the report and therefore not necessarily the name of the default reason) / Données utilisables: _Id_ (identifiant du signalement), _Reported_ (pseudo du joueur signalé), _Reporter_ (pseudo du joueur signaleur, la commande est exécutée pour chaque signaleur s'il y en a plusieurs), _Staff_ (pseudo du membre du staff qui traite le signalement) et _Reason_ (raison du signalement et donc pas forcément le nom de la sanction par défaut)
  # PunishCommandsPermission:    Permission required to execute the punish commands listed under PunishCommands / Permission requise pour exécuter les commandes de sanction listées dans PunishCommands
  
  Punishments:
    Enabled: yes
    # Open the punishments menu or execute the command below when processing a report as True / Ouvrir le menu des sanctions ou exécuter la commande ci-dessous lors du traitement d'un signalement comme Vrai
    
    PunishmentsCommand: none
    # Replace the punishments menu with a command executed by the staff who process the report / Remplacer le menu des sanctions par une commande exécutée par le membre de l'équipe qui traite le signalement
    # Note that the _Reporter_ placeholder will be replaced by the first reporter, not all to avoid a spam of commands / A noter que le placeholder _Reporter_ sera remplacé par le premier signaleur, et non tous pour éviter d'exécuter plusieurs commandes
    
    DefaultReasons: yes
    # Use defaults reasons as punishments / Utiliser les raisons par défaut comme des sanctions
    # "PunishCommands:" property must be added below each default reason / La propriété "PunishCommands:" doit être ajoutée en-dessous de chaque raison par défaut
    
    Punishment1:
      Name: "R\xe9cidive de triche"
      Lore: "&7Le joueur r\xe9utilise un hack."
      # "&7The player use a hack again."
      Item: Material-TNT
      PunishCommands:
      - "ban _Reported_ 1m R\xe9cidive de triche"
    Punishment2:
      Name: "Harc\u00E8lement"
      Lore: "&7Le joueur harc\u00E8le les autres."
      # "&7The player harasses others."
      Item: Material-Pumpkin
      PunishCommands:
      - "ban _Reported_ 7d Harc\u00E8lement"
  # Punishments available after processing a report as True / Sanctions disponibles après avoir traité un signalement comme vrai
  # Name:    Name of the punsihment / Nom de la sanction
  # Lore:    Description of the punishment / Description de la sanction
  # Item:    Material-<item_type>(:damage) or/ou Skull-<pseudo>
  #   Examples:    Material-Stone = Stone / Pierre    Material-Wool:2 = Magenta Wool / Laine magenta    Skull-MrTigreroux = Skull of player MrTigreroux / Tête du joueur MrTigreroux
  #   Material names (used for <item_type> placeholder) depend on the Spigot version used on your server.
  #     Spigot 1.8 material names: https://helpch.at/docs/1.8/org/bukkit/Material.html
  #     Spigot 1.13 material names: https://helpch.at/docs/1.13/org/bukkit/Material.html
  #     Spigot latest version material names: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # PunishCommands:    List of commands to execute when punishing / Liste des commandes à exécuter lors d'une sanction.
  #                    Set '-CONSOLE' at the beginning of a command to execute it with the console (and not the staff member) / Mettre "-CONSOLE" au début d'une commande pour l'exécuter avec la console (et non le membre de la modération)
  #                    Usable placeholders: _Id_ (id of the report), _Reported_ (reported player name), _Reporter_ (reporter player name, the command is executed for each reporter if they are multiple), _Staff_ (processor staff name) and _Reason_ (reason of the report and not the name of the punishment) / Données utilisables: _Id_ (identifiant du signalement), _Reported_ (pseudo du joueur signalé), _Reporter_ (pseudo du joueur signaleur, la commande est exécutée pour chaque signaleur s'il y en a plusieurs), _Staff_ (pseudo du membre du staff qui traite le signalement) et _Reason_ (raison du signalement et non le nom de la sanction)
  # PunishCommandsPermission:    Permission required to execute the punish commands listed under PunishCommands / Permission requise pour exécuter les commandes de sanction listées dans PunishCommands
  
  ChatReport:
    Enabled: no
    # Use the format configured below for all player chat messages. This feature isn't compatible with any other chat manager plugin. / Utiliser le format de messages configuré ci-dessous. Cette fonctionnalité n'est compatible avec aucun autre plugin de gestion du chat
    
    Message: "_ReportButton_ _DisplayName_&7: _Message_"
    # Chat messages format / Format des messages du chat
    
    ReportButton:
      Text: "&7[&c&l!&7]"
      # Report button display in chat / Apparence du bouton de signalement
      
      Hover: "&6Clic gauche &7pour signaler le message du joueur &e_Player_&7." # "Left click to report the message of _Player_ player."
      # Message displayed when hovering the report button / Message affiché en survolant le bouton de signalement
      
      Reason: "Message inappropri\xe9" # "Inappropriate message"
      # Report reason when using the report button / Raison du signalement envoyé lorsque le bouton de signalement est utilisé

BungeeCord:
  Enabled: yes
  # Interact with the BungeeCord network / Intéragir avec le réseau BungeeCord
  
  Servers:
    server1: "Serveur 1"
  # Custom display name of servers / Nom personnalisé des serveurs

MySQL:
  Host: ""
  Port: 0
  Database: ""
  Username: ""
  Password: ""
  UseSSL: no
  VerifyServerCertificate: no
# Login IDs of connection to a MySQL database / Identifiants de connexion à une base de données MySQL

VaultChat:
  Enabled: yes
  # Use prefixes and suffixes from the chat of Vault plugin to display player names / Utiliser les préfixes et suffixes du chat du plugin Vault pour afficher les noms des joueurs
  
  Format: "_Prefix__Name__Suffix_"
  # Format used to display player names / Format utilisé pour afficher les noms des joueurs
  
  DisplayForStaff: yes
  # Use prefixes and suffixes from the chat of Vault plugin to display staff names / Utiliser les préfixes et suffixes du chat du plugin Vault pour afficher les noms des membres de l'équipe (staff)
  
  DisplayForPlayers: no
  # Use prefixes and suffixes from the chat of Vault plugin to display reported and reporters names / Utiliser les préfixes et suffixes du chat du plugin Vault pour afficher les noms des joueurs signalés et signaleurs